### ISSUE TITLE
Список метрик

### ISSUE THREAD

**Issue by Konohomaru** [Konohomaru/GiraBot#2]
- [x] Мартин Фаулер [о командной работе](https://martinfowler.com/).
- [x] Изучить [диаграмму Miro](https://miro.com/app/board/o9J_kvElAWc=/).
- [x] Что [это за компания](https://www.thoughtworks.com/)?
- [x] Полистать [книгу](https://www.amazon.com/Accelerate-Software-Performing-Technology-Organizations/dp/1942788339).
- [x] [Битая ссылка](https://sci-hub.se/) на бесплатный дистрибьютер научной литературы.

### DoD:

Есть конкретный список метрик.

**Comment by Konohomaru** [comment]
**Sprint Velocity**. Показывает какими типами задач (полосами в терминологии Mindbox) и в каком количестве занималась команда разработчиков в течении спринта. На данный момент определено три типа задач: bugs, road map, tech debt.

**Comment by Konohomaru** [comment]
**Sprint burndown**. Наглядно показывает прогресс выполнения задач. Актуально для текущего спринта.

**Comment by Konohomaru** [comment]
**Task cycle time**. Метрика для подсчёта длительности выполнения задач. Показывает статистическое соотношение сложности задач ко времени их выполнения.

**Comment by Konohomaru** [comment]
Возможно, [sci-hub.do](https://sci-hub.do/) и есть тот самый бесплатный дистрибьютер научной литературы?
